project:
  type: website
  output-dir: docs

website:
  title: Emma Pajak
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/emmapajak/
      - icon: github
        menu:
          - text: My Github - EmPajak21
            url:  https://github.com/EmPajak21
          - text: Report a Bug
            url:  ttps://github.com/EmPajak21
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


  
    